### ISSUE TITLE
svg css conflict with non-nvd3 charts

### ISSUE THREAD

**Issue by isadaqah** [novus/nvd3#494]
svg css is modifying style in non-nvd3 charts. It would be great if it can be namespaced like the rest of the styles.

I am referring to these:

```
svg {
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
  /* Trying to get SVG to act like a greedy block in all browsers */
  display: block;
  width:100%;
  height:100%;
}

svg text {
  font: normal 12px Arial;
}

svg .title {
 font: bold 14px Arial;
}
```

**Comment by liquidpele** [comment]
Been fixed in the community fork for a while...

https://github.com/nvd3-community/nvd3

**Comment by facultymatt** [comment]
Thanks @liquidpele for this information - I didn't realize nvd3-community existed.

I am using nvd3-angular, which unfortunately still depends on the original nvd3... however as noted by https://github.com/krispo/angular-nvd3/issues/66 it might be possible to use nvd3-community with no conflicts... I will give it a try!

**Comment by liquidpele** [comment]
fixed in latest.

**Comment by joshuahhh** [comment]
@liquidpele -- What do you mean by "fixed in latest"? Currently, the first selector in https://github.com/novus/nvd3/blob/master/src/nv.d3.css is a bare `svg`, so I think the problem is still present here. Do you mean that you expect the changes from the community fork to be merged back into this repo?

**Comment by liquidpele** [comment]
I mean in the latest of the development branch

**Comment by nishantkmr** [comment]
The issue still exists. 
https://github.com/nvd3-community/nvd3/blob/master/src/nv.d3.css
Please fix it.
